name: Build, Push and Deploy DS to DockerHub

on:
    push:
        branches:
          - main
    pull_request:
        types: [opened, reopened, edited]
        branches:
          - main
    workflow_dispatch:


env:
  # À compléter avec vos secrets DockerHub
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  REPO_API: api-gateway
  REPO_CLIENT: client-service
  REPO_ACCOUNT: account-service


jobs:

  build:
    name: Build and Push Images to DockerHub
    runs-on: ubuntu-latest
    steps:
      # Checkout code (à compléter)
      - name: Récupérer le code
        uses: actions/checkout@v4
# Installer Java (à compléter)
      - name: Installer Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      
     

      # Se connecter à DockerHub (à compléter)
      - name: Se connecter à DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

     
      

      # Build API Gateway (à compléter)
      - name: b&p api gateway
        working-directory: ds-api-gateway
        run: |
          mvn clean package -DskipTests
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.REPO_API }}:latest .
          docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.REPO_API }}:latest
      # working-directory: ds-api-gateway
      # run: |
      - name: b&p client service
        working-directory: ds-client-service
        run: |
          mvn clean package -DskipTests
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.REPO_CLIENT }}:latest .
          docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.REPO_CLIENT }}:latest
      # Build Client Service (à compléter)
      # working-directory: ds-client-service
      # run: |
      - name: b&p account service
        working-directory: ds-account-service
        run: |
          mvn clean package -DskipTests
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.REPO_ACCOUNT }}:latest .
          docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.REPO_ACCOUNT }}:latest
      # Build Account Service (à compléter)
      # working-directory: ds-account-service

  deploy:
    
    name: Deploy All Services
    runs-on: ubuntu-latest
    # définir la dépendance avec le job build
    needs: build
    steps:
      - name: Simulate deployment
        run: 
          echo "Simulating deployment of all services"|
         
